# This is a basic workflow to help you get started with Actions

name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      
      - name: Configure Docker
        run: |
          docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set version tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.IMAGENAME }}:${{ steps.vars.outputs.sha_short }}
