# This is a basic workflow to help you get started with Actions

name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      # - name: Set up Docker Build
      #   uses: docker/setup-buildx-action@v1
        
      # - name: Configure Docker
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ secrets.REGISTRY_URL }}
      #     username: ${{ secrets.REGISTRY_USERNAME  }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Checkout branches
        uses: actions/checkout@v2
      
      - name: Get lastest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Get new tag
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch
  
      # - name: Push new tag
      #   uses: actions-ecosystem/action-push-tag@v1
      #   with:
      #     tag: ${{ steps.bump-semver.outputs.new_version }}
      
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ secrets.IMAGENAME }}:${{ steps.bump-semver.outputs.current_version }}

      - name: Command Group
        run: |
          echo '${{ steps.bump-semver.outputs.current_version }}'

      # - name: Deploy Caprover
      #   uses: floms/action-caprover@v1
      #   with:
      #       host: '${{ secrets.CAPROVER_HOST }}'
      #       password: '${{ secrets.CAPROVER_PASSWORD }}'
      #       app: '${{ secrets.CAPROVER_APP_NAME }}'
      #       image: '${{ secrets.IMAGENAME }}:${{ steps.bump-semver.outputs.current_version }}'
